sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t forrestmoon/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true forrestmoon/react-test npm test

after_success:
  - docker build -t forrestmoon/multi-client ./client
  - docker build -t forrestmoon/multi-nginx ./nginx
  - docker build -t forrestmoon/multi-server ./server
  - docker build -t forrestmoon/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push forrestmoon/multi-client
  - docker push forrestmoon/multi-nginx
  - docker push forrestmoon/multi-server
  - docker push forrestmoon/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: redasys-multi-docker
  bucket_name: elasticbeanstalk-us-east-2-795369863836
  bucket_path: redasys-docker-multi
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
